local-conf.in: drop TCLIBCAPPEND
:Release Notes:
Dropped in:
https://git.openembedded.org/openembedded-core/commit/?id=ebcd355a32e2711263e22d9b45b502696ecbb4d2
and marked as deprecated variable in:
https://git.openembedded.org/openembedded-core/commit/?id=992ba784c168710328749fd61a0e2869df519dea

:Detailed Notes:
Fixes:
ERROR: Variable TCLIBCAPPEND is no longer used, modify TMPDIR directly
if required (file: styhead/conf/local.conf line: 477)