build-templates/local-conf.in: bump CONF_VERSION
:Release Notes:
Follow LOCALCONF_VERSION change:
https://git.openembedded.org/openembedded-core/commit/?id=5452f1ba337685cf89d3429e08255450ab90b96f

:Detailed Notes:
Unfortunately users will still need to adjust their webos-local.conf or
webos-global.conf to use new syntax and they won't get the error message
like bellow, because CONF_VERSION is set in local.conf part managed by
mcf, so it will force them to re-run mcf.status or "mcf --command configure"
but not to update their local modifications in webos-*.conf.

ERROR: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:oecore_update_localconf(d)
     0003:
File: '/jenkins/home/anaconda/build-webos-ose-ros-honister/build/oe-core/meta/classes/sanity.bbclass', lineno: 56, function: oecore_update_localconf
     0052:
     0053:is a good way to visualise the changes."""
     0054:    failmsg = d.expand(failmsg)
     0055:
 *** 0056:    raise NotImplementedError(failmsg)
     0057:}
     0058:
     0059:SANITY_SITECONF_SAMPLE ?= "${COREBASE}/meta*/conf/site.conf.sample"
     0060:python oecore_update_siteconf() {
Exception: NotImplementedError: Your version of local.conf was generated from an older/newer version of
local.conf.sample and there have been updates made to this file. Please compare the two
files and merge any changes before continuing.

Matching the version numbers will remove this message.

"meld conf/local.conf /jenkins/home/anaconda/build-webos-ose-ros-honister/build/oe-core/meta*/conf/local.conf.sample"

is a good way to visualise the changes.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-141293] Create GPVB with Yocto 3.4 Honister

Change-Id: I5e2f92555c19541b64a1c3171e1bf3d0f3cdf96c