mcf: Catch failed git remote update (v6.2.4)
:Release Notes:
Catch more exception and replace LOCATIONS with layer["location"]

:Detailed Notes:
LOCATIONS variable isn't defined since v6.2.0:
  commit 230d2a3e1f8c710b13867f8aa8a78f1d615a4fa1
  Author: Martin Jansa <martin.jansa@lge.com>
  Date:   Fri Apr 21 16:20:27 2017 +0000

    mcf: Replace many global hashmaps with one (v6.2.0)

    :Release Notes:
    Having all information related to given layer in one hashmap makes
    it easier to debug and extend MCF functionality.

It wasn't catched until now, because it happens only when git remote
update fails immediately after after changing remote url which we don't
do very often:
Traceback (most recent call last):
  File "./mcf", line 901, in <module>
    update_layers(srcdir)
  File "./mcf", line 478, in update_layers
    if reposanitycheck(layer) != 0:
  File "./mcf", line 589, in reposanitycheck
    raise Exception('Failed to fetch %s repo' % LOCATIONS[layer])
NameError: name 'LOCATIONS' is not defined

Rethrow the same Exception in other places where we run git remote
update to make sure that the name of failed repository is written
at the end of the exception, the log is still a bit ugly, but better
than not showing which layer failed to fetch:

2020-03-11T07:38:21 INFO __main__ Updating [meta-webosose]
fatal: remote error:
  Repository not found.
error: Could not fetch fail
Traceback (most recent call last):
  File "./mcf", line 712, in updaterepo
    echo_check_call("git remote update")
  File "./mcf", line 48, in echo_check_call
    return str(subprocess.check_output(cmd, shell=True), encoding='utf-8', errors='strict')
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'git remote update' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./mcf", line 907, in <module>
    update_layers(srcdir)
  File "./mcf", line 482, in update_layers
    updaterepo(layer)
  File "./mcf", line 715, in updaterepo
    raise Exception('Failed to fetch %s repo' % layer["location"])
Exception: Failed to fetch meta-webosose repo

or when wrong commit is specified:
2020-03-11T07:55:00 INFO __main__ Updating [meta-webosose]
2020-03-11T07:55:00 INFO __main__ MCF-6.2.4: trying to fetch revision 20331bd in /jenkins/mjansa/build-webos-github-master/meta-webosose attempt 1 from 30
fatal: ambiguous argument '20331bd': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "./mcf", line 727, in updaterepo
    echo_check_call(cmd)
  File "./mcf", line 48, in echo_check_call
    return str(subprocess.check_output(cmd, shell=True), encoding='utf-8', errors='strict')
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'git reset --hard 20331bd' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./mcf", line 928, in <module>
    update_layers(srcdir)
  File "./mcf", line 491, in update_layers
    updaterepo(layer)
  File "./mcf", line 729, in updaterepo
    raise Exception('Failed to fetch %s repo' % layer["location"])
Exception: Failed to fetch meta-webosose repo

:Testing Performed:

:QA Notes:
N/A

:Issues Addressed:
[PLAT-102271] Various webos.inc fixes and cleanups
[PLAT-102385] CCC: Various webos.inc fixes and cleanups

Change-Id: I40b8d7cc55b8c9b25c413a3aafa3d948491ea492